[anytrack] # <tracker-name>
label = anytrack
protocol = traxpython
command =  anytrack_depthTrack
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /home/sqh/lihao/AnyTrack/lib/test/vot
